// Selection tree structure mapping shapes to categories to duct IDs
export const categoriesMap: Record<string, Record<string, string[]>> = {
  Round: {
    Elbows: ["A7A", "A7B", "A7C"],
    "Transitions (Diverging Flow)": ["A8A", "A8C"],
    "Transitions (Converging Flow)": ["A9A1", "A9B1", "A9D"],
    "Converging Junctions (Tees, Wyes)": ["A10A", "A10B", "A10E", "A10I1"],
    "Diverging Junctions (Tees, Wyes)": [
      "A11A",
      "A11B",
      "A11C",
      "A11D",
      "A11E",
      "A11F",
      "A11G",
      "A11H",
      "A11I",
      "A11J",
      "A11K",
      "A11L",
      "A11M",
    ],
    Entries: ["A12A", "A12B", "A12C", "A12D", "A12E", "A12F", "A12G"],
  },
  Rectangular: {
    Elbows: ["A7D", "A7E", "A7F", "A7G", "A7H1", "A7H2", "A7I", "A7J", "A7L"],
    "Transitions (Diverging Flow)": [
      "A8B",
      "A8D",
      "A8E",
      "A8F",
      "A8G",
      "A8H",
      "A8I",
      "A8J",
    ],
    "Transitions (Converging Flow)": ["A9A2", "A9B2", "A9C"],
    "Converging Junctions (Tees, Wyes)": [
      "A10C",
      "A10D",
      "A10F",
      "A10G",
      "A10H",
      "A10I2",
    ],
    "Diverging Junctions (Tees, Wyes)": [
      "A11N",
      "A11O",
      "A11P",
      "A11Q",
      "A11R",
      "A11S",
      "A11T",
      "A11U",
      "A11V",
      "A11W",
    ],
    Entries: [],
  },
};
