import { DuctDefinition } from "./types";

// Helper to create placeholder duct definition
const createPlaceholderDuct = (
  id: string,
  fitting: string,
  fittingType: string,
  caseName: string,
  shape: "round" | "rectangular"
): DuctDefinition => ({
  id,
  fitting,
  fittingType,
  name: `${id} - ${caseName}`,
  shape,
  inputs: [
    { entryKey: "entry_1", label: "Input 1", type: "number", unitHint: "TBD" },
    { entryKey: "entry_2", label: "Input 2", type: "number", unitHint: "TBD" },
    { entryKey: "entry_3", label: "Input 3", type: "number", unitHint: "TBD" },
    { entryKey: "entry_4", label: "Input 4", type: "number", unitHint: "TBD" },
  ],
  outputs: [
    { key: "output_1", label: "Velocity (ft/min)" },
    { key: "output_2", label: "Vel. Pres @ V0 (in w.c.)" },
    { key: "output_3", label: "Loss Coefficient" },
    { key: "output_4", label: "Pressure Loss (in w.c.)" },
  ],
});

export const ductDefinitions: DuctDefinition[] = [
  // Round > Elbows
  {
    id: "A7A",
    fitting: "Elbow",
    fittingType: "Round, Smooth Radius",
    name: "A7A - Round Elbow, Smooth Radius, 90°",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D (in)", type: "number", unitHint: "Diameter" },
      { entryKey: "entry_2", label: "R/D", type: "number", unitHint: "Radius to Diameter ratio" },
      { entryKey: "entry_3", label: "Angle (deg)", type: "number", unitHint: "Bend angle" },
      { entryKey: "entry_4", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (ft/min)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in w.c.)" },
    ],
  },
  {
    id: "A7B",
    fitting: "Elbow",
    fittingType: "Round, Mitered",
    name: "A7B - Round Elbow, Mitered",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D (in)", type: "number", unitHint: "Diameter" },
      { entryKey: "entry_2", label: "R/D", type: "number", unitHint: "Radius to Diameter ratio" },
      { entryKey: "entry_3", label: "# pieces", type: "number", unitHint: "Number of pieces" },
      { entryKey: "entry_4", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A7C",
    fitting: "Elbow",
    fittingType: "Round, Smooth Radius (R/D < 0.5)",
    name: "A7C - Round Elbow, Smooth Radius (R/D < 0.5)",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D (in)", type: "number", unitHint: "Diameter" },
      { entryKey: "entry_2", label: "Angle (deg)", type: "number", unitHint: "Bend angle" },
      { entryKey: "entry_3", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A7D",
    fitting: "Elbow",
    fittingType: "Rectangular, Mitered",
    name: "A7D - Rectangular Elbow, Mitered",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "Angle (deg)", type: "number", unitHint: "Bend angle" },
      { entryKey: "entry_4", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A7E",
    fitting: "Elbow",
    fittingType: "Rectangular, Radiused",
    name: "A7E - Rectangular Elbow, Radiused",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "W₁ (in)", type: "number", unitHint: "Inner width" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_4", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A7F",
    fitting: "Elbow",
    fittingType: "Rectangular, Radiused (Angle < 90°)",
    name: "A7F - Rectangular Elbow, Radiused (Angle < 90°)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "R (in)", type: "number", unitHint: "Radius" },
      { entryKey: "entry_4", label: "θ (deg)", type: "number", unitHint: "Angle" },
      { entryKey: "entry_5", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },

  // Round > Transitions (Diverging Flow)
  {
    id: "A8A",
    fitting: "Transition",
    fittingType: "Conical Expansion",
    name: "A8A - Conical Expansion",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D (in)", type: "number", unitHint: "Diameter" },
      { entryKey: "entry_2", label: "D₁ (in)", type: "number", unitHint: "Expanded diameter" },
      { entryKey: "entry_3", label: "Angle (deg)", type: "number", unitHint: "Expansion angle" },
      { entryKey: "entry_4", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A8C",
    fitting: "Transition",
    fittingType: "Round to Rectangular",
    name: "A8C - Round to Rectangular Expansion",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "D (in)", type: "number", unitHint: "Diameter" },
      { entryKey: "entry_4", label: "L (in)", type: "number", unitHint: "Length" },
      { entryKey: "entry_5", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },

  // Round > Transitions (Converging Flow)
  {
    id: "A9A1",
    fitting: "Transition",
    fittingType: "Conical Contraction",
    name: "A9A1 - Round Conical Contraction",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D (in)", type: "number", unitHint: "Diameter" },
      { entryKey: "entry_2", label: "D₁ (in)", type: "number", unitHint: "Contracted diameter" },
      { entryKey: "entry_3", label: "Angle (deg)", type: "number", unitHint: "Contraction angle" },
      { entryKey: "entry_4", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  createPlaceholderDuct("A9B1", "Transition", "Stepped Conical Contraction", "Stepped Conical Contraction", "round"),
  createPlaceholderDuct("A9D", "Transition", "Round to Rectangular", "Round to Rectangular Contraction", "round"),

  // Round > Converging Junctions
  createPlaceholderDuct("A10A", "Junction", "Converging Tee, Round", "Converging Tee, Round", "round"),
  createPlaceholderDuct("A10B", "Junction", "Converging Wye, Round", "Converging Wye, Round", "round"),
  createPlaceholderDuct("A10E", "Junction", "Converging Wye, Rectangular Main to Round Branch", "Converging Wye, Rectangular Main to Round Branch", "round"),
  createPlaceholderDuct("A10I1", "Junction", "Converging 45° Wye, Round", "Converging 45° Wye, Round", "round"),

  // Round > Diverging Junctions
  createPlaceholderDuct("A11A", "Junction", "Tee, Round, Straight Main, Conical Branch, 0°", "Tee, Round, Straight Main, Conical Branch, 0°", "round"),
  createPlaceholderDuct("A11B", "Junction", "Tee, Round, Straight Main, Conical Branch, 30°", "Tee, Round, Straight Main, Conical Branch, 30°", "round"),
  createPlaceholderDuct("A11C", "Junction", "Tee, Round, Straight Main, Conical Branch, 45°", "Tee, Round, Straight Main, Conical Branch, 45°", "round"),
  createPlaceholderDuct("A11D", "Junction", "Tee, Round, Straight Main, Conical Branch, 60°", "Tee, Round, Straight Main, Conical Branch, 60°", "round"),
  createPlaceholderDuct("A11E", "Junction", "Tee, Round, Straight Main, Conical Branch, 90°", "Tee, Round, Straight Main, Conical Branch, 90°", "round"),
  createPlaceholderDuct("A11F", "Junction", "Tee, Round, Straight Main, Tapered Branch, 90°", "Tee, Round, Straight Main, Tapered Branch, 90°", "round"),
  createPlaceholderDuct("A11G", "Junction", "Tee, Round, Straight Main, Round Branch, 45°", "Tee, Round, Straight Main, Round Branch, 45°", "round"),
  createPlaceholderDuct("A11H", "Junction", "Wye, Round, 45°, Curved Main", "Wye, Round, 45°, Curved Main", "round"),
  createPlaceholderDuct("A11I", "Junction", "Wye, Round, 45°, Rectangular Main", "Wye, Round, 45°, Rectangular Main", "round"),
  createPlaceholderDuct("A11J", "Junction", "Tee, Round Reducer", "Tee, Round Reducer", "round"),
  createPlaceholderDuct("A11K", "Junction", "Tee, Rectangular Main to Round Branch, Conical", "Tee, Rectangular Main to Round Branch, Conical", "round"),
  createPlaceholderDuct("A11L", "Junction", "Wye, Round, 45°, Converging Reducer", "Wye, Round, 45°, Converging Reducer", "round"),
  createPlaceholderDuct("A11M", "Junction", "Tee, Round, Tapered Main, Round Branch, 90°", "Tee, Round, Tapered Main, Round Branch, 90°", "round"),

  // Round > Entries
  createPlaceholderDuct("A12A", "Entry", "Round, Free Discharge", "Entry, Round, Free Discharge", "round"),
  createPlaceholderDuct("A12B", "Entry", "Round, Flush", "Entry, Round, Flush", "round"),
  createPlaceholderDuct("A12C", "Entry", "Round, Radiused", "Entry, Round, Radiused", "round"),
  createPlaceholderDuct("A12D", "Entry", "Round, Bellmouth", "Entry, Round, Bellmouth", "round"),
  createPlaceholderDuct("A12E", "Entry", "Round, Conical", "Entry, Round, Conical", "round"),
  createPlaceholderDuct("A12F", "Entry", "Intake Hood", "Intake Hood", "round"),
  createPlaceholderDuct("A12G", "Entry", "Hood, Tapered, Flanged or Unflanged", "Hood, Tapered, Flanged or Unflanged", "round"),

  // Rectangular > Elbows (already defined A7D, A7E, A7F above)
  {
    id: "A7G",
    fitting: "Elbow",
    fittingType: "Rectangular, Smooth Radius with Splitter Vanes",
    name: "A7G - Rectangular Elbow with Splitter Vanes",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "R (in)", type: "number", unitHint: "Radius" },
      { entryKey: "entry_4", label: "# Vanes", type: "number", unitHint: "Number of vanes" },
      { entryKey: "entry_5", label: "Angle (deg)", type: "number", unitHint: "Bend angle" },
      { entryKey: "entry_6", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  createPlaceholderDuct("A7H1", "Elbow", "Mitered with Single Thickness Turning Vanes", "Mitered with Single Thickness Turning Vanes", "rectangular"),
  createPlaceholderDuct("A7H2", "Elbow", "Mitered with Double Thickness Turning Vanes", "Mitered with Double Thickness Turning Vanes", "rectangular"),
  {
    id: "A7I",
    fitting: "Elbow",
    fittingType: "Rectangular, Z-Shaped",
    name: "A7I - Rectangular Offset (Z-Shaped)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "L (in)", type: "number", unitHint: "Length" },
      { entryKey: "entry_4", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A7J",
    fitting: "Elbow",
    fittingType: "Rectangular, Different Planes",
    name: "A7J - Rectangular Offset (Different Planes)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "L (in)", type: "number", unitHint: "Length" },
      { entryKey: "entry_4", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A7K",
    fitting: "Elbow",
    fittingType: "Round Offset",
    name: "A7K - Round Offset",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D (in)", type: "number", unitHint: "Diameter" },
      { entryKey: "entry_2", label: "L (in)", type: "number", unitHint: "Length" },
      { entryKey: "entry_3", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  createPlaceholderDuct("A7L", "Elbow", "Wye or Tee Shape", "Wye or Tee Shape", "rectangular"),

  // Rectangular > Transitions (Diverging Flow)
  {
    id: "A8B",
    fitting: "Transition",
    fittingType: "Pyramidal Expansion",
    name: "A8B - Rectangular Expansion",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "H₁ (in)", type: "number", unitHint: "Height 1" },
      { entryKey: "entry_4", label: "W₁ (in)", type: "number", unitHint: "Width 1" },
      { entryKey: "entry_5", label: "Angle (deg)", type: "number", unitHint: "Expansion angle" },
      { entryKey: "entry_6", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A8D",
    fitting: "Transition",
    fittingType: "Rectangular to Round",
    name: "A8D - Rectangular to Round Transition",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "D (in)", type: "number", unitHint: "Diameter" },
      { entryKey: "entry_4", label: "L (in)", type: "number", unitHint: "Length" },
      { entryKey: "entry_5", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A8E",
    fitting: "Transition",
    fittingType: "Rectangular, Sides Straight",
    name: "A8E - Rectangular Expansion (Sides Straight)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "H₁ (in)", type: "number", unitHint: "Height 1" },
      { entryKey: "entry_3", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_4", label: "Angle (deg)", type: "number", unitHint: "Expansion angle" },
      { entryKey: "entry_5", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A8F",
    fitting: "Transition",
    fittingType: "Symmetric at Fan with Duct Sides Straight",
    name: "A8F - Rectangular Expansion (Symmetric at Fan)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "H₁ (in)", type: "number", unitHint: "Height 1" },
      { entryKey: "entry_3", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_4", label: "Angle (deg)", type: "number", unitHint: "Expansion angle" },
      { entryKey: "entry_5", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A8G",
    fitting: "Transition",
    fittingType: "Asymmetric at Fan with Sides Straight, Top Level",
    name: "A8G - Rectangular Expansion (Asymmetric, Top Level)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "H₁ (in)", type: "number", unitHint: "Height 1" },
      { entryKey: "entry_3", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_4", label: "Angle (deg)", type: "number", unitHint: "Expansion angle" },
      { entryKey: "entry_5", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A8H",
    fitting: "Transition",
    fittingType: "Asymmetric at Fan with Sides Straight, Top 10° Down",
    name: "A8H - Rectangular Expansion (Asymmetric, Top 10° Down)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "H₁ (in)", type: "number", unitHint: "Height 1" },
      { entryKey: "entry_3", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_4", label: "Angle (deg)", type: "number", unitHint: "Expansion angle" },
      { entryKey: "entry_5", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A8I",
    fitting: "Transition",
    fittingType: "Asymmetric at Fan with Sides Straight, Top 10° Up",
    name: "A8I - Rectangular Expansion (Asymmetric, Top 10° Up)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "H₁ (in)", type: "number", unitHint: "Height 1" },
      { entryKey: "entry_3", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_4", label: "Angle (deg)", type: "number", unitHint: "Expansion angle" },
      { entryKey: "entry_5", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A8J",
    fitting: "Transition",
    fittingType: "Pyramidal at Fan with Duct",
    name: "A8J - Rectangular Expansion (Pyramidal at Fan)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "H₁ (in)", type: "number", unitHint: "Height 1" },
      { entryKey: "entry_4", label: "W₁ (in)", type: "number", unitHint: "Width 1" },
      { entryKey: "entry_5", label: "Angle (deg)", type: "number", unitHint: "Expansion angle" },
      { entryKey: "entry_6", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },

  // Rectangular > Transitions (Converging Flow)
  {
    id: "A9A2",
    fitting: "Transition",
    fittingType: "Pyramidal Contraction",
    name: "A9A2 - Rectangular Pyramidal Contraction",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "H₁ (in)", type: "number", unitHint: "Height 1" },
      { entryKey: "entry_4", label: "W₁ (in)", type: "number", unitHint: "Width 1" },
      { entryKey: "entry_5", label: "Angle (deg)", type: "number", unitHint: "Contraction angle" },
      { entryKey: "entry_6", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A9B1",
    fitting: "Transition",
    fittingType: "Stepped Conical Contraction",
    name: "Round Conical Contraction with Length",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D (in)", type: "number", unitHint: "Diameter" },
      { entryKey: "entry_2", label: "D₁ (in)", type: "number", unitHint: "Diameter 1" },
      { entryKey: "entry_3", label: "L (in)", type: "number", unitHint: "Length" },
      { entryKey: "entry_4", label: "Angle (°)", type: "number", unitHint: "Angle" },
      { entryKey: "entry_5", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A9B2",
    fitting: "Transition",
    fittingType: "Stepped Pyramidal Contraction",
    name: "Rectangular Pyramidal Contraction with Length",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H (in)", type: "number", unitHint: "Height" },
      { entryKey: "entry_2", label: "W (in)", type: "number", unitHint: "Width" },
      { entryKey: "entry_3", label: "H₁ (in)", type: "number", unitHint: "Height 1" },
      { entryKey: "entry_4", label: "W₁ (in)", type: "number", unitHint: "Width 1" },
      { entryKey: "entry_5", label: "L (in)", type: "number", unitHint: "Length" },
      { entryKey: "entry_6", label: "Angle (°)", type: "number", unitHint: "Angle" },
      { entryKey: "entry_7", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A9C",
    fitting: "Transition",
    fittingType: "Round to Rectangular",
    name: "Round to Rectangular Transition",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D (in)", type: "number", unitHint: "Round diameter" },
      { entryKey: "entry_2", label: "H₁ (in)", type: "number", unitHint: "Rectangular height" },
      { entryKey: "entry_3", label: "W₁ (in)", type: "number", unitHint: "Rectangular width" },
      { entryKey: "entry_4", label: "Q (cfm)", type: "number", unitHint: "Flow rate" },
    ],
    outputs: [
      { key: "output_1", label: "Velocity (fpm)" },
      { key: "output_2", label: "Vel. Pres @ V0 (in. w.c.)" },
      { key: "output_3", label: "Loss Coefficient" },
      { key: "output_4", label: "Pressure Loss (in. w.c.)" },
      { key: "output_5", label: "Flag" },
    ],
  },

  // Round > Converging Junctions
  {
    id: "A10A1",
    fitting: "Junction",
    fittingType: "Converging Tee",
    name: "Round Tee, 45° Entry Branch",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D main (in)", type: "number", unitHint: "Main diameter" },
      { entryKey: "entry_2", label: "D branch (in)", type: "number", unitHint: "Branch diameter" },
      { entryKey: "entry_3", label: "Q source (cfm)", type: "number", unitHint: "Source flow" },
      { entryKey: "entry_4", label: "Q branch (cfm)", type: "number", unitHint: "Branch flow" },
    ],
    outputs: [
      { key: "output_1", label: "Branch: Velocity (fpm)" },
      { key: "output_2", label: "Branch: Vel. Pres (in. w.c.)" },
      { key: "output_3", label: "Branch: Loss Coefficient" },
      { key: "output_4", label: "Branch: Pressure Loss (in. w.c.)" },
      { key: "output_5", label: "Main: Velocity (fpm)" },
      { key: "output_6", label: "Main: Vel. Pres (in. w.c.)" },
      { key: "output_7", label: "Main: Loss Coefficient" },
      { key: "output_8", label: "Main: Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A10B",
    fitting: "Junction",
    fittingType: "Converging Tee",
    name: "Round Tee, 30° Entry Branch",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D main (in)", type: "number", unitHint: "Main diameter" },
      { entryKey: "entry_2", label: "D branch (in)", type: "number", unitHint: "Branch diameter" },
      { entryKey: "entry_3", label: "Q source (cfm)", type: "number", unitHint: "Source flow" },
      { entryKey: "entry_4", label: "Q branch (cfm)", type: "number", unitHint: "Branch flow" },
    ],
    outputs: [
      { key: "output_1", label: "Branch: Velocity (fpm)" },
      { key: "output_2", label: "Branch: Vel. Pres (in. w.c.)" },
      { key: "output_3", label: "Branch: Loss Coefficient" },
      { key: "output_4", label: "Branch: Pressure Loss (in. w.c.)" },
      { key: "output_5", label: "Main: Velocity (fpm)" },
      { key: "output_6", label: "Main: Vel. Pres (in. w.c.)" },
      { key: "output_7", label: "Main: Loss Coefficient" },
      { key: "output_8", label: "Main: Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A10E",
    fitting: "Junction",
    fittingType: "Converging Tee",
    name: "Round Tee, 45° Entry Branch (Different Diameters)",
    shape: "round",
    inputs: [
      { entryKey: "entry_1", label: "D source (in)", type: "number", unitHint: "Source diameter" },
      { entryKey: "entry_2", label: "D converging (in)", type: "number", unitHint: "Converging diameter" },
      { entryKey: "entry_3", label: "D branch (in)", type: "number", unitHint: "Branch diameter" },
      { entryKey: "entry_4", label: "Q source (cfm)", type: "number", unitHint: "Source flow" },
      { entryKey: "entry_5", label: "Q branch (cfm)", type: "number", unitHint: "Branch flow" },
    ],
    outputs: [
      { key: "output_1", label: "Branch: Velocity (fpm)" },
      { key: "output_2", label: "Branch: Vel. Pres (in. w.c.)" },
      { key: "output_3", label: "Branch: Loss Coefficient" },
      { key: "output_4", label: "Branch: Pressure Loss (in. w.c.)" },
      { key: "output_5", label: "Main: Velocity (fpm)" },
      { key: "output_6", label: "Main: Vel. Pres (in. w.c.)" },
      { key: "output_7", label: "Main: Loss Coefficient" },
      { key: "output_8", label: "Main: Pressure Loss (in. w.c.)" },
    ],
  },

  // Rectangular > Converging Junctions
  {
    id: "A10C",
    fitting: "Junction",
    fittingType: "Converging Tee",
    name: "Rectangular Tee, 45° Entry Branch (Ab = Ac/2)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H main (in)", type: "number", unitHint: "Main height" },
      { entryKey: "entry_2", label: "W main (in)", type: "number", unitHint: "Main width" },
      { entryKey: "entry_3", label: "Q source (cfm)", type: "number", unitHint: "Source flow" },
      { entryKey: "entry_4", label: "Q branch (cfm)", type: "number", unitHint: "Branch flow" },
    ],
    outputs: [
      { key: "output_1", label: "Branch: Velocity (fpm)" },
      { key: "output_2", label: "Branch: Vel. Pres (in. w.c.)" },
      { key: "output_3", label: "Branch: Loss Coefficient" },
      { key: "output_4", label: "Branch: Pressure Loss (in. w.c.)" },
      { key: "output_5", label: "Main: Velocity (fpm)" },
      { key: "output_6", label: "Main: Vel. Pres (in. w.c.)" },
      { key: "output_7", label: "Main: Loss Coefficient" },
      { key: "output_8", label: "Main: Pressure Loss (in. w.c.)" },
    ],
  },
  {
    id: "A10D",
    fitting: "Junction",
    fittingType: "Converging Tee",
    name: "Rectangular Tee, 30° Entry Branch (Ab = Ac/2)",
    shape: "rectangular",
    inputs: [
      { entryKey: "entry_1", label: "H main (in)", type: "number", unitHint: "Main height" },
      { entryKey: "entry_2", label: "W main (in)", type: "number", unitHint: "Main width" },
      { entryKey: "entry_3", label: "Q source (cfm)", type: "number", unitHint: "Source flow" },
      { entryKey: "entry_4", label: "Q branch (cfm)", type: "number", unitHint: "Branch flow" },
    ],
    outputs: [
      { key: "output_1", label: "Branch: Velocity (fpm)" },
      { key: "output_2", label: "Branch: Vel. Pres (in. w.c.)" },
      { key: "output_3", label: "Branch: Loss Coefficient" },
      { key: "output_4", label: "Branch: Pressure Loss (in. w.c.)" },
      { key: "output_5", label: "Main: Velocity (fpm)" },
      { key: "output_6", label: "Main: Vel. Pres (in. w.c.)" },
      { key: "output_7", label: "Main: Loss Coefficient" },
      { key: "output_8", label: "Main: Pressure Loss (in. w.c.)" },
    ],
  },
  createPlaceholderDuct("A10F", "Junction", "Tee, 45° Entry Branch to Rectangular Main", "Tee, 45° Entry Branch to Rectangular Main", "rectangular"),
  createPlaceholderDuct("A10G", "Junction", "Symmetrical Wye, Dovetail", "Symmetrical Wye, Dovetail", "rectangular"),
  createPlaceholderDuct("A10H", "Junction", "Converging Rectangular Wye", "Converging Rectangular Wye", "rectangular"),
  createPlaceholderDuct("A10I2", "Junction", "Symmetrical Wye", "Symmetrical Wye", "rectangular"),

  // Rectangular > Diverging Junctions
  createPlaceholderDuct("A11N", "Junction", "Tee, 45° Rectangular Main & Branch", "Tee, 45° Rectangular Main & Branch", "rectangular"),
  createPlaceholderDuct("A11O", "Junction", "Tee, 45° Entry, Rectangular Main & Branch with Damper", "Tee, 45° Entry, Rectangular Main & Branch with Damper", "rectangular"),
  createPlaceholderDuct("A11P", "Junction", "Tee, Rectangular Main & Branch", "Tee, Rectangular Main & Branch", "rectangular"),
  createPlaceholderDuct("A11Q", "Junction", "Tee, Rectangular Main & Branch with Damper", "Tee, Rectangular Main & Branch with Damper", "rectangular"),
  createPlaceholderDuct("A11R", "Junction", "Tee, Rectangular Main & Branch with Extractor", "Tee, Rectangular Main & Branch with Extractor", "rectangular"),
  createPlaceholderDuct("A11S", "Junction", "Tee, Rectangular Main to Round Branch", "Tee, Rectangular Main to Round Branch", "rectangular"),
  createPlaceholderDuct("A11T", "Junction", "Rectangular Wye, Main Straight", "Rectangular Wye, Main Straight", "rectangular"),
  createPlaceholderDuct("A11U", "Junction", "Tee, Rectangular Main to Conical Branch", "Tee, Rectangular Main to Conical Branch", "rectangular"),
  createPlaceholderDuct("A11V", "Junction", "90° Curved Rectangular Wye", "90° Curved Rectangular Wye", "rectangular"),
  createPlaceholderDuct("A11W", "Junction", "Symmetrical Wye, Dovetail", "Symmetrical Wye, Dovetail", "rectangular"),
];
